name: image build and scan 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -f ./star-agile-banking-finance/pom.xml clean package -DskipTests  

    - name: log into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/gems-app:${{ github.sha }} -f ./star-agile-banking-finance/Dockerfile ./star-agile-banking-finance

    - name: trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ github.repository_owner }}/gems-app:${{ github.sha }}
        format: 'sarif'
        output: ./star-agile-banking-finance/trivy-report.sarif
        exit-code: '1'
        severity: 'CRITICAL,HIGH,MEDIUM'
        ignore-unfixed: true

    - name: Upload trivy report to GitHub security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ./star-agile-banking-finance/trivy-report.sarif

    
